---
ssh_port: 3127

jenkins_port: 8080
jenkins_java_packages:
  - fontconfig
  - openjdk-21-jre
jenkins_gpg_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
jenkins_gpg_key_path: "/usr/share/keyrings/jenkins-keyring.asc"
jenkins_repo: "deb [signed-by={{ jenkins_gpg_key_path }}] https://pkg.jenkins.io/debian-stable binary/"
jenkins_list_path: "/etc/apt/sources.list.d/jenkins.list"
jenkins_service_name: "jenkins"

minio_bin_url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
minio_bin_path: "/usr/local/bin/minio"
minio_user: "minio-user"
minio_group: "minio-user"
minio_storage_dir: "/data/minio"
minio_env_file: "/etc/default/minio"
minio_access_key: "minioadmin"
minio_secret_key: "MinIO@gVm261"
minio_service_file: "/etc/systemd/system/minio.service"
minio_console_port: 9001

postgresql_packages:
  - postgresql
  - postgresql-contrib
postgresql_service_name: postgresql
postgresql_version: "16"
postgresql_conf_dir: "/etc/postgresql/16/main"
postgresql_conf_file: "/etc/postgresql/16/main/postgresql.conf"
pg_hba_conf_file: "/etc/postgresql/16/main/pg_hba.conf"
postgresql_listen_addresses: "*"
postgresql_password: "Base!AgVm!261"

docker_packages:
  - docker.io
  - docker-compose-plugin

docker_service_name: docker
docker_group: docker

docker_user: "{{ ansible_user }}"
docker_users:
  - "agvmdigital"

pgadmin_network: pgnetwork
pgadmin_container_name: pgadmin
pgadmin_image: dpage/pgadmin4
pgadmin_restart_policy: always
pgadmin_port: 5050
pgadmin_email: technicien@tsirylab.com
pgadmin_password: "PgAgVM!261"
pgadmin_data_volume: pgadmin_data

portainer_namespace: portainer
portainer_release_name: portainer
portainer_chart_version: 1.0.47
portainer_nodeport: 30777
portainer_storage_size: 10Gi

k3s_bin_path: /usr/local/bin/k3s
k3s_kubeconfig: /etc/rancher/k3s/k3s.yaml

users_create:
  - name: agvmdigital
    password: "{{ 'AgVm@Vp!s' | password_hash('sha512') }}"
    groups: "sudo"
    shell: /bin/bash

proxy_apps:
  #- domain: jenkins
  #  port: 8080
  #  websocket: true
  #- domain: portainer
  #  port: 30777
  #  websocket: true
  #- domain: dashboard
  #  port: 30002
  #  websocket: true
  - domain: harbor
    port: 30003
    client_max_body_size: 2G
  #- domain: gateway-dev
  #  port: 5020
  #  websocket: true
  - domain: minio
    port: 9001
    websocket: true
  - domain: pgadmin
    port: 5050
    websocket: true

kubeconfig_path: /etc/rancher/k3s/k3s.yaml
dashboard_manifest_url: "https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml"
dashboard_nodeport: 30002
admin_user_manifest: "/tmp/dashboard-admin-user.yaml"

harbor_namespace: harbor
harbor_admin_password: "AgVm@harbor"
harbor_nodeport_http: 30003
harbor_nodeport_https: 32443
harbor_persistence_size_registry: "5Gi"
harbor_persistence_size_chartmuseum: "5Gi"
harbor_persistence_size_jobservice: "1Gi"
harbor_persistence_size_database: "1Gi"
harbor_persistence_size_redis: "1Gi"
harbor_persistence_size_trivy: "5Gi"
harbor_url: "harbor.agvm.tsirylab.com"
k8s_secret_name: jenkins-harbor-secret
k8s_secret_namespace: default
k8s_secret_email: technicien@tsirylab.com
jenkins_harbor_password: "AgVm@Vp!s"
jenkins_harbor_username: admin
