---
# Tâches pour installer et configurer PostgreSQL

- name: Mettre à jour le système
  apt:
    update_cache: yes
    upgrade: dist

- name: Installer PostgreSQL et les paquets complémentaires
  apt:
    name: "{{ postgresql_packages }}"
    state: present

- name: Vérifier la version de PostgreSQL
  command: psql --version
  register: psql_version
  changed_when: false

- name: Démarrer et activer le service PostgreSQL
  service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: yes

- name: Changer le mot de passe de l'utilisateur 'postgres'
  become: yes
  command: su - postgres -c "psql -c \"ALTER USER postgres PASSWORD '{{ postgresql_password }}';\""
  args:
    executable: /bin/bash

- name: Autoriser l'écoute sur toutes les adresses (listen_addresses)
  become: yes
  lineinfile:
    path: "{{ postgresql_conf_file }}"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '{{ postgresql_listen_addresses }}'"
    state: present

- name: Autoriser l'accès distant via pg_hba.conf
  become: yes
  lineinfile:
    path: "{{ pg_hba_conf_file }}"
    insertafter: EOF
    line: "host    all             all             0.0.0.0/0               md5"
    state: present

- name: Redémarrer PostgreSQL
  become: yes
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
