- name: Installer NGINX
  apt:
    name: nginx
    state: present

- name: Vérifier la config NGINX
  command: nginx -t

- name: Redémarrer NGINX
  service:
    name: nginx
    state: restarted

- name: Activer NGINX
  service:
    name: nginx
    enabled: yes

- name: Installer Certbot et plugin NGINX
  become: yes
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes
