---
- name: Installer Docker si besoin
  apt:
    name: docker.io
    state: present

- name: Créer le réseau Docker pour PostgreSQL et pgAdmin
  docker_network:
    name: "{{ pgadmin_network }}"
    state: present

- name: Déployer le conteneur pgAdmin
  docker_container:
    name: "{{ pgadmin_container_name }}"
    image: "{{ pgadmin_image }}"
    restart_policy: "{{ pgadmin_restart_policy }}"
    networks:
      - name: "{{ pgadmin_network }}"
    published_ports:
      - "{{ pgadmin_port }}:80"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
    volumes:
      - "{{ pgadmin_data_volume }}:/var/lib/pgadmin"
    state: started

- name: Installer Nginx
  apt:
    name: nginx
    state: present

- name: Créer la configuration Nginx pour pgAdmin
  copy:
    dest: "{{ nginx_pgadmin_conf }}"
    content: |
      server {
          server_name {{ pgadmin_domain }};
          location / {
              proxy_pass http://localhost:{{ pgadmin_port }};
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    owner: root
    group: root
    mode: '0644'

- name: Activer le site Nginx pour pgAdmin
  file:
    src: "{{ nginx_pgadmin_conf }}"
    dest: "/etc/nginx/sites-enabled/pgadmin.itdcmada.mg"
    state: link

- name: Vérifier la configuration Nginx
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Redémarrer Nginx
  service:
    name: nginx
    state: restarted

# Pour la partie SSL, tu peux ajouter ce bloc si Certbot est installé :
- name: Générer le certificat SSL avec Let's Encrypt (Certbot)
  command: >
    certbot --nginx -d {{ pgadmin_domain }}
  args:
    creates: "/etc/letsencrypt/live/{{ pgadmin_domain }}/fullchain.pem"
  when: pgadmin_domain is defined

- name: Afficher accès pgAdmin
  debug:
    msg: "Accède à pgAdmin sur : https://{{ pgadmin_domain }} avec {{ pgadmin_email }} / {{ pgadmin_password }}"