---
- name: Installer Docker si besoin
  apt:
    name: docker.io
    state: present

- name: Créer le réseau Docker pour PostgreSQL et pgAdmin
  docker_network:
    name: "{{ pgadmin_network }}"
    state: present

- name: Déployer le conteneur pgAdmin
  docker_container:
    name: "{{ pgadmin_container_name }}"
    image: "{{ pgadmin_image }}"
    restart_policy: "{{ pgadmin_restart_policy }}"
    networks:
      - name: "{{ pgadmin_network }}"
    published_ports:
      - "{{ pgadmin_port }}:80"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
    volumes:
      - "{{ pgadmin_data_volume }}:/var/lib/pgadmin"
    state: started
