---
- name: Mettre à jour le système
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Installer unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configurer unattended-upgrades
  dpkg_reconfigure:
    package: unattended-upgrades
    priority: low

- name: Sécuriser SSH - Désactiver root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Sécuriser SSH - Changer le port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Port'
    line: 'Port {{ ssh_port }}'

- name: Sécuriser SSH - Désactiver mot de passe
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Sécuriser SSH - Désactiver ChallengeResponseAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'

- name: Sécuriser SSH - Désactiver UsePAM
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM'
    line: 'UsePAM no'

- name: Redémarrer SSH
  service:
    name: ssh
    state: restarted

- name: Installer fail2ban
  apt:
    name: fail2ban
    state: present

- name: Copier la config Fail2Ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: S'assurer que Fail2Ban est actif
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Installer et configurer UFW
  apt:
    name: ufw
    state: present

- name: Configurer UFW - règles SSH
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Configurer UFW - HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Configurer UFW - HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Définir la politique par défaut - entrées
  ufw:
    direction: incoming
    policy: deny

- name: Définir la politique par défaut - sorties
  ufw:
    direction: outgoing
    policy: allow

- name: Activer UFW
  ufw:
    state: enabled
