---
# Tâches pour configurer le pare-feu Firewalld

- name: Installer le pare-feu Firewalld
  dnf:
    name: firewalld
    state: present
    update_cache: yes

- name: Définir la politique par défaut (entrant deny)
  firewalld:
    zone: public
    target: DROP
    permanent: yes
    state: enabled
    immediate: yes

- name: Définir la politique par défaut (sortant allow)
  firewalld:
    zone: public
    outgoing_interface: default
    permanent: yes

- name: Autoriser SSH
  firewalld:
    port: "{{ ssh_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Autoriser HTTP
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Autoriser HTTPS
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Autoriser le port PostgreSQL
  firewalld:
    port: 5432/tcp
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Activer Firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Afficher le statut Firewalld
  command: firewall-cmd --state
  register: fw_status

- name: Afficher les règles Firewalld
  debug:
    msg: "{{ fw_status.stdout }}"
