- name: Installer K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  register: k3s_install
  changed_when: "'already installed' not in (k3s_install.stdout | default(''))"

- name: Vérifier que le fichier kubeconfig existe
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_config

- name: Modifier les permissions du fichier kubeconfig
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'
    owner: root
    group: root
  when: k3s_config.stat.exists

- name: Vérifier que K3s est opérationnel
  command: kubectl get nodes
  register: k3s_status
  changed_when: false
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Afficher le statut des nodes
  debug:
    var: k3s_status.stdout