---
- name: Vérifier si Helm est déjà installé
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_bin

- name: Installer Helm (si absent)
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: not helm_bin.stat.exists
  become: true
- name: "Portainer | Add Helm repository"
  kubernetes.core.helm_repository:
    name: portainer
    repo_url: https://portainer.github.io/k8s/
  environment:
    KUBECONFIG: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

- name: "Portainer | Create namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ portainer_namespace }}"
    state: present
  environment:
    KUBECONFIG: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

- name: "Portainer | Install via Helm"
  kubernetes.core.helm:
    name: "{{ portainer_release_name }}"
    chart_ref: portainer/portainer
    chart_version: "{{ portainer_chart_version }}"
    release_namespace: "{{ portainer_namespace }}"
    create_namespace: true
    values:
      service:
        type: NodePort
        nodePort: "{{ portainer_nodeport }}"
      persistence:
        enabled: true
        size: "{{ portainer_storage_size }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

- name: "Portainer | Wait for deployment"
  kubernetes.core.k8s_info:
    kind: Deployment
    name: "{{ portainer_release_name }}"
    namespace: "{{ portainer_namespace }}"
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_sleep: 5
    wait_timeout: 180
  environment:
    KUBECONFIG: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"