---
- name: Mettre à jour le système
  apt:
    update_cache: yes
    upgrade: dist

- name: Créer le volume Docker pour Portainer
  docker_volume:
    name: "{{ portainer_data_volume }}"
    state: present

- name: Lancer le conteneur Portainer
  docker_container:
    name: "{{ portainer_container_name }}"
    image: "{{ portainer_image }}"
    restart_policy: "{{ portainer_restart_policy }}"
    published_ports:
      - "{{ portainer_api_port }}:{{ portainer_internal_api_port }}"
      - "{{ portainer_web_port }}:{{ portainer_internal_web_port }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ portainer_data_volume }}:/data"
    state: started

- name: Installer Nginx
  apt:
    name: nginx
    state: present

- name: Créer la configuration Nginx pour Portainer
  copy:
    dest: "{{ nginx_portainer_conf }}"
    content: |
      server {
          server_name {{ portainer_domain }};

          location / {
              proxy_pass http://localhost:{{ portainer_web_port }};
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;

              # Support des WebSockets
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
          }
      }
    owner: root
    group: root
    mode: '0644'

- name: Activer le site Nginx pour Portainer
  file:
    src: "{{ nginx_portainer_conf }}"
    dest: "/etc/nginx/sites-enabled/portainer.itdcmada.mg"
    state: link

- name: Vérifier la configuration Nginx
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Redémarrer Nginx
  service:
    name: nginx
    state: restarted

# Pour la partie SSL, tu peux ajouter ce bloc si Certbot est installé :
- name: Générer le certificat SSL avec Let's Encrypt (Certbot)
  command: >
    certbot --nginx -d {{ portainer_domain }}
  args:
    creates: "/etc/letsencrypt/live/{{ portainer_domain }}/fullchain.pem"
  when: portainer_domain is defined

- name: Afficher accès Portainer
  debug:
    msg: "Accède à Portainer sur : https://{{ portainer_domain }}"