---
- name: Installer Java (prérequis Jenkins)
  dnf:
    name:
      - java-21-openjdk-devel
      - fontconfig
    state: present
    update_cache: yes

- name: Créer le répertoire pour les clés
  file:
    path: /etc/pki/rpm-gpg
    state: directory
    mode: '0755'

- name: Télécharger la clé GPG Jenkins (nouvelle méthode)
  get_url:
    url: "{{ jenkins_gpg_key_url }}"
    dest: "{{ jenkins_gpg_key_path }}"
    mode: '0644'
    force: yes

- name: Ajouter le dépôt Jenkins avec signature
  yum_repository:
    name: jenkins
    description: Jenkins Repository
    baseurl: "https://pkg.jenkins.io/redhat-stable"
    gpgcheck: yes
    gpgkey: "{{ jenkins_gpg_key_path }}"
    state: present
    enabled: yes

- name: Mettre à jour le cache DNF après ajout du dépôt
  dnf:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer Jenkins
  dnf:
    name: jenkins
    state: present
    update_cache: no

- name: Modifier le port d'écoute de Jenkins
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "^HTTP_PORT="
    line: "HTTP_PORT={{ jenkins_port }}"
    backup: yes
  notify: Redémarrer Jenkins

- name: S'assurer que Jenkins est lancé et activé
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Autoriser le port d'écoute de Jenkins
  firewalld:
    port: "{{ jenkins_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes