---
- name: Installer Docker et Docker Compose
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Démarrer et activer le service Docker
  service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: yes

- name: Ajouter l'utilisateur au groupe docker
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: yes

- name: Appliquer le nouveau groupe (newgrp docker)
  shell: newgrp docker
  args:
    executable: /bin/bash
  when: docker_user == ansible_user
  register: newgrp_result
  changed_when: false