---
- name: Vérifier que kubectl est installé
  command: kubectl version --client
  register: kubectl_check
  failed_when: kubectl_check.rc != 0

- name: Vérifier que Helm est installé
  command: helm version
  register: helm_check
  failed_when: helm_check.rc != 0

- name: Ajouter le repo Helm Harbor
  command: helm repo add harbor https://helm.goharbor.io
  register: add_repo
  changed_when: "'already exists' not in add_repo.stdout"

- name: Mettre à jour les repos Helm
  command: helm repo update

- name: "Harbor | Create namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ harbor_namespace }}"
    state: present
  environment:
    KUBECONFIG: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

- name: Créer le fichier de valeurs Harbor
  template:
    src: harbor-values.yaml.j2
    dest: /tmp/harbor-values.yaml

- name: Installer Harbor via Helm
  kubernetes.core.helm:
    name: harbor
    chart_ref: harbor/harbor
    release_namespace: "{{ harbor_namespace }}"
    values_files:
      - /tmp/harbor-values.yaml
    state: present
    wait: true
    timeout: "600s"
  environment:
    KUBECONFIG: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"
